Add missing type from reac-native package
When typechecking with typescript, the following error is being thrown:
- node_modules/lottie-react-native/src/js/index.d.ts(126,24): error TS2304: Cannot find name 'LayoutChangeEvent'